name: kpenfound fork of dawidd6 Homebrew bump formula
description: Bump (update) a Homebrew formula on new project release
author: kpenfound
branding:
  icon: arrow-up-circle
  color: yellow
inputs:
  token:
    description: GitHub token (not the default one)
    required: true
  tap:
    description: |
      Formula tap.

      In livecheck mode, if formula input is empty,
      the Action will check the whole tap.

      Example: kpenfound/tap
      Example: kpenfound/homebrew-tap
    required: false
  formula:
    description: |
      Formula name.

      In livecheck mode, this could take more than one formula,
      separated by commas or spaces or newlines.

      Example: lazygit
      Example (livecheck): lazygit, lazydocker, lazynpm
    required: false
  tag:
    description: |
      Git tag.

      It is determined automatically.

      Example: v1.0.0
      Example: refs/tags/v1.0.0
    required: false
    default: ${{github.ref}}
  revision:
    description: |
      Git revision.

      Only required for formulae that use git to download the source.

      It is determined automatically.

      Example: 130d3a3af72f66780ae4e24cd143ae7a4d757f9d
    required: false
    default: ${{github.sha}}
  nofork:
    description: Pass --no-fork to brew
    required: false
  force:
    description: Check open PRs or not (will fail if detected)
    required: false
  livecheck:
    description: |
      Use `brew livecheck` to determine outdated formulae.

      If tap input is specified - check all formulae in this tap.
      If formula input is specified - check one or more formulae.
      If formula and tap inputs are specified - check one or more formulae in that tap.
    required: false
runs:
  using: node12
  main: main.js
