name: Test Action

on:
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        formula:
          - test-formula-url
          - test-formula-git-kpenfound
        include:
          - formula: test-formula-url
            tap: dawidd6/test
            tag: v0.1.12
            force: true
          - formula: test-formula-git-kpenfound
            tap: dawidd6/test
            tag: v0.3.3
            kpenfound: c43abd765cf51c06bbcaa5479dc49aab1396989f
            force: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: ./
        with:
          token: ${{secrets.TOKEN}}
          tap: ${{matrix.tap}}
          formula: ${{matrix.formula}}
          tag: ${{matrix.tag}}
          kpenfound: ${{matrix.kpenfound}}
          force: ${{matrix.force}}
  test-livecheck-formula:
    runs-on: macos-latest
    needs:
      - test
    steps:
      - name: Wait
        run: sleep 30
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: ./
        with:
          token: ${{secrets.TOKEN}}
          formula: test-formula-url, test-formula-git-kpenfound
          tap: dawidd6/test
          force: true
          livecheck: true
  test-livecheck-tap:
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
    needs:
      - test-livecheck-formula
    steps:
      - name: Wait
        run: sleep 30
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: ./
        with:
          token: ${{secrets.TOKEN}}
          tap: dawidd6/test
          force: true
          livecheck: true
